<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-7QOC93L" name="testcases.dbconnector" tests="11" failures="5" timestamp="2022-11-08T14:50:20 IST" time="214.270" errors="0">
  <testcase name="TC_HM_003_parameterize_dbfetch_util" time="11.364" classname="testcases.dbconnector">
    <failure type="java.lang.AssertionError" message="Not matching expected [28] but found [49]">
      <![CDATA[java.lang.AssertionError: Not matching expected [28] but found [49]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at pages.UsedCarPage.verifynoofbrands(UsedCarPage.java:43)
at testcases.dbconnector.TC_HM_003_parameterize_dbfetch_util(dbconnector.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
]]>
    </failure>
  </testcase> <!-- TC_HM_003_parameterize_dbfetch_util -->
  <system-out/>
  <testcase name="TC_HM_003_parameterize_dbfetch_util" time="11.896" classname="testcases.dbconnector">
    <skipped/>
  </testcase> <!-- TC_HM_003_parameterize_dbfetch_util -->
  <system-out/>
  <testcase name="TC_HM_003_parameterize_dbfetch_util" time="26.495" classname="testcases.dbconnector">
    <skipped/>
  </testcase> <!-- TC_HM_003_parameterize_dbfetch_util -->
  <system-out/>
  <testcase name="TC_HM_003_parameterize_dbfetch_util" time="10.042" classname="testcases.dbconnector"/>
  <system-out/>
  <testcase name="TC_HM_003_parameterize_dbfetch_util" time="16.398" classname="testcases.dbconnector">
    <skipped/>
  </testcase> <!-- TC_HM_003_parameterize_dbfetch_util -->
  <system-out/>
  <testcase name="TC_HM_003_parameterize_dbfetch_util" time="23.913" classname="testcases.dbconnector">
    <failure type="java.lang.AssertionError" message="Not matching expected [32] but found [49]">
      <![CDATA[java.lang.AssertionError: Not matching expected [32] but found [49]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at pages.UsedCarPage.verifynoofbrands(UsedCarPage.java:43)
at testcases.dbconnector.TC_HM_003_parameterize_dbfetch_util(dbconnector.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
]]>
    </failure>
  </testcase> <!-- TC_HM_003_parameterize_dbfetch_util -->
  <system-out/>
  <testcase name="TC_HM_003_parameterize_dbfetch_util" time="15.403" classname="testcases.dbconnector">
    <failure type="java.lang.AssertionError" message="Not matching expected [35] but found [49]">
      <![CDATA[java.lang.AssertionError: Not matching expected [35] but found [49]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at pages.UsedCarPage.verifynoofbrands(UsedCarPage.java:43)
at testcases.dbconnector.TC_HM_003_parameterize_dbfetch_util(dbconnector.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
]]>
    </failure>
  </testcase> <!-- TC_HM_003_parameterize_dbfetch_util -->
  <system-out/>
  <testcase name="TC_HM_003_parameterize_dbfetch_util" time="21.599" classname="testcases.dbconnector">
    <failure type="java.lang.AssertionError" message="Not matching expected [31] but found [49]">
      <![CDATA[java.lang.AssertionError: Not matching expected [31] but found [49]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at pages.UsedCarPage.verifynoofbrands(UsedCarPage.java:43)
at testcases.dbconnector.TC_HM_003_parameterize_dbfetch_util(dbconnector.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
]]>
    </failure>
  </testcase> <!-- TC_HM_003_parameterize_dbfetch_util -->
  <system-out/>
  <testcase name="TC_HM_003_parameterize_dbfetch_util" time="10.660" classname="testcases.dbconnector">
    <skipped/>
  </testcase> <!-- TC_HM_003_parameterize_dbfetch_util -->
  <system-out/>
  <testcase name="TC_HM_003_parameterize_dbfetch_util" time="31.695" classname="testcases.dbconnector">
    <failure type="java.lang.AssertionError" message="Not matching expected [31] but found [49]">
      <![CDATA[java.lang.AssertionError: Not matching expected [31] but found [49]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at pages.UsedCarPage.verifynoofbrands(UsedCarPage.java:43)
at testcases.dbconnector.TC_HM_003_parameterize_dbfetch_util(dbconnector.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
]]>
    </failure>
  </testcase> <!-- TC_HM_003_parameterize_dbfetch_util -->
  <system-out/>
  <testcase name="TC_HM_003_parameterize_dbfetch_util" time="34.805" classname="testcases.dbconnector">
    <skipped/>
  </testcase> <!-- TC_HM_003_parameterize_dbfetch_util -->
  <system-out/>
</testsuite> <!-- testcases.dbconnector -->
